name: Build, Test, and Report Coverage

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl libssl-dev
          curl -sL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Restore dependencies
        run: dotnet restore ./Tests/OrderFlowBot.Tests.csproj

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: dotnet test ./Tests/OrderFlowBot.Tests.csproj --configuration Release

  coverage:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y python3 curl bash

      - name: Download and Install DeepSource CLI
        run: |
          # Set installation directory
          INSTALL_DIR=/root/.deepsource/bin

          # Download the script
          curl -L https://deepsource.io/cli -o deepsource-cli.sh

          # Set executable permissions
          chmod +x deepsource-cli.sh

          # Install the CLI to the specified directory
          ./deepsource-cli.sh -b $INSTALL_DIR

          # Add the binary directory to PATH
          export PATH="$PATH:$INSTALL_DIR"

      - name: Run Tests and Generate Coverage
        run: |
          dotnet test ./Tests/OrderFlowBot.Tests.csproj --configuration Release \
            --collect:"XPlat Code Coverage" \
            --results-directory ./TestResults

      - name: Upload Coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          export PATH="$PATH:/root/.deepsource/bin"
          deepsource report \
            --analyzer test-coverage \
            --key csharp \
            --value-file $(find ./TestResults -name "coverage.cobertura.xml")
