name: Build, Test, and Report Coverage

on:
  push:
  pull_request:

jobs:
  coverage:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y python3 curl bash git
          dotnet tool install --global dotnet-coverage

      - name: Configure Git
        run: |
          git config --global --add safe.directory "*"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Create TestResults Directory
        run: mkdir -p TestResults

      - name: Restore Dependencies
        run: dotnet restore ./Tests/OrderFlowBot.Tests.csproj

      - name: Generate Coverage
        run: |
          dotnet-coverage collect 'dotnet test ./Tests/OrderFlowBot.Tests.csproj' -f cobertura -o ./TestResults/coverage.cobertura.xml

      - name: Download and Install DeepSource CLI
        run: |
          curl https://deepsource.io/cli | sh

      - name: Debug Information
        run: |
          echo "Current directory content:"
          ls -la
          echo "TestResults directory content:"
          ls -la TestResults
          echo "Full path search for coverage file:"
          find . -name "coverage.cobertura.xml"
          echo "Current working directory:"
          pwd

      - name: Upload Coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          if [ -f "./TestResults/coverage.cobertura.xml" ]; then
            ./bin/deepsource report \
              --analyzer test-coverage \
              --key csharp \
              --value-file ./TestResults/coverage.cobertura.xml
          else
            echo "Coverage file not found!"
            exit 1
          fi
