name: Build, Test, and Report Coverage

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          apt-get update
          apt-get install -y curl libssl-dev
          curl -sL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Restore dependencies
        run: dotnet restore ./Tests/OrderFlowBot.Tests.csproj

  test:
    needs: build
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run Tests
        run: dotnet test ./Tests/OrderFlowBot.Tests.csproj --configuration Release

  coverage:
    needs: test
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:8.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Install Dependencies
        run: |
          apt-get update
          apt-get install -y python3 curl bash git

      - name: Configure Git
        run: |
          git config --global --add safe.directory "*"
          git config --global user.email "actions@github.com"
          git config --global user.name "GitHub Actions"

      - name: Download and Install DeepSource CLI
        run: |
          curl https://deepsource.io/cli | sh

      - name: Run Tests and Generate Coverage
        run: |
          dotnet tool install --global coverlet.console
          dotnet test ./Tests/OrderFlowBot.Tests.csproj \
            --configuration Release \
            /p:CollectCoverage=true \
            /p:CoverletOutputFormat=cobertura \
            /p:CoverletOutput=$GITHUB_WORKSPACE/TestResults/coverage.cobertura.xml

      - name: Debug Coverage File
        run: |
          echo "Current directory content:"
          ls -la
          echo "TestResults directory content:"
          ls -la $GITHUB_WORKSPACE/TestResults
          echo "Coverage file location:"
          find $GITHUB_WORKSPACE -name "coverage.cobertura.xml"
          echo "Coverage file content preview:"
          head -n 10 $GITHUB_WORKSPACE/TestResults/coverage.cobertura.xml

      - name: Upload Coverage to DeepSource
        env:
          DEEPSOURCE_DSN: ${{ secrets.DEEPSOURCE_DSN }}
        run: |
          ./bin/deepsource report \
            --analyzer test-coverage \
            --key csharp \
            --value-file $GITHUB_WORKSPACE/TestResults/coverage.cobertura.xml
