name: CI Workflow

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and dependencies for libssl
        run: |
          apt-get update
          apt-get install -y curl libssl-dev
          curl -sL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Restore dependencies
        run: dotnet restore ./Tests/OrderFlowBot.Tests.csproj

      - name: Build
        run: dotnet build ./Tests/OrderFlowBot.Tests.csproj --configuration Release

  test:
    runs-on: ubuntu-latest
    needs: build
    container:
      image: mcr.microsoft.com/dotnet/sdk:5.0

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Node.js and dependencies for libssl
        run: |
          apt-get update
          apt-get install -y curl libssl-dev
          curl -sL https://deb.nodesource.com/setup_20.x | bash -
          apt-get install -y nodejs

      - name: Run Tests
        run: dotnet test ./Tests/OrderFlowBot.Tests.csproj --no-build --configuration Release
